Set itsdangerous package to 2.0.1
Since import of JSON is deprecated from itsdangerous version 2.1.0 [1], this patch fixes the version to 2.0.1.
By fixing to version, we can avoid the below import error.
Error "from itsdangerous import json as _json ImportError: cannot import name 'json' from 'itsdangerous'"

[1] https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-1-0